# Generated by Django 2.2.4 on 2019-08-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='name')),
            ],
            options={
                'db_table': 'author',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='name')),
                ('summary', models.CharField(blank=True, max_length=300, verbose_name='summary')),
                ('author', models.ManyToManyField(to='Application.Author')),
            ],
            options={
                'db_table': 'book',
            },
        ),
    ]
